export const lolRegions = {
  NA: 'North America',
  EU: 'Europe',
  KR: 'Korea',
  CN: 'China',
  LCK: 'LCK',
  LCS: 'LCS',
  LEC: 'LEC',
  LPL: 'LPL',
  BR: 'Brazil',
  TR: 'Turkey',
  LAN: 'Latin America North',
  LAS: 'Latin America South',
  OCE: 'Oceania',
  JP: 'Japan',
  VN: 'Vietnam',
  RU: 'Russia',
  SEA: 'Southeast Asia',
};

export const lolTournaments = {
  Worlds: 'League of Legends World Championship (Worlds)',
  MSI: 'Mid-Season Invitational (MSI)',
  LCS: 'League of Legends Championship Series (LCS)',
  LEC: 'League of Legends European Championship (LEC)',
  LCK: 'League of Legends Champions Korea (LCK)',
  LPL: 'League of Legends Pro League (LPL)',
  LMS: 'League of Legends Master Series (LMS)',
  LLN: 'Latin America League (LLN)',
  CBLOL: 'Campeonato Brasileiro de League of Legends (CBLOL)',
  LJL: 'League of Legends Japan League (LJL)',
};

export const lolTeams = {
  fnatic: 'Fnatic',
  g2: 'G2 Esports',
  skt: 'T1 (formerly SK Telecom T1)',
  damwon: 'DAMWON Gaming',
  cloud9: 'Cloud9',
  tsm: 'Team SoloMid (TSM)',
  rng: 'Royal Never Give Up (RNG)',
  fpx: 'FunPlus Phoenix (FPX)',
  edg: 'Edward Gaming (EDG)',
  gen_g: 'Gen.G Esports',
  liquid: 'Team Liquid',
  fnc: 'FunPlus Phoenix (FPX)',
  ig: 'Invictus Gaming (IG)',
  rogue: 'Rogue',
  vitality: 'Team Vitality',
  mad: 'MAD Lions',
  drx: 'DRX (DragonX)',
  immortals: 'Immortals',
  '100t': '100 Thieves',
  lgd: 'LGD Gaming',
};
