export const lolRegions = {
  NA: 'North America',
  EU: 'Europe',
  KR: 'Korea',
  CN: 'China',
  LCK: 'LCK',
  LCS: 'LCS',
  LEC: 'LEC',
  LPL: 'LPL',
  BR: 'Brazil',
  TR: 'Turkey',
  LAN: 'Latin America North',
  LAS: 'Latin America South',
  OCE: 'Oceania',
  JP: 'Japan',
  VN: 'Vietnam',
  RU: 'Russia',
  SEA: 'Southeast Asia',
};

export const lolTournaments = {
  Worlds: 'League of Legends World Championship (Worlds)',
  MSI: 'Mid-Season Invitational (MSI)',
  LCS: 'League of Legends Championship Series (LCS)',
  LEC: 'League of Legends European Championship (LEC)',
  LCK: 'League of Legends Champions Korea (LCK)',
  LPL: 'League of Legends Pro League (LPL)',
  LMS: 'League of Legends Master Series (LMS)',
  LLN: 'Latin America League (LLN)',
  CBLOL: 'Campeonato Brasileiro de League of Legends (CBLOL)',
  LJL: 'League of Legends Japan League (LJL)',
};
