export const lolRegions = {
  NA: 'North America',
  EU: 'Europe',
  KR: 'Korea',
  CN: 'China',
  LCK: 'LCK',
  LCS: 'LCS',
  LEC: 'LEC',
  LPL: 'LPL',
  BR: 'Brazil',
  TR: 'Turkey',
  LAN: 'Latin America North',
  LAS: 'Latin America South',
  OCE: 'Oceania',
  JP: 'Japan',
  VN: 'Vietnam',
  RU: 'Russia',
  SEA: 'Southeast Asia',
};

export const lolTournaments = {
  Worlds: 'League of Legends World Championship (Worlds)',
  MSI: 'Mid-Season Invitational (MSI)',
  LCS: 'League of Legends Championship Series (LCS)',
  LEC: 'League of Legends European Championship (LEC)',
  LCK: 'League of Legends Champions Korea (LCK)',
  LPL: 'League of Legends Pro League (LPL)',
  LMS: 'League of Legends Master Series (LMS)',
  LLN: 'Latin America League (LLN)',
  CBLOL: 'Campeonato Brasileiro de League of Legends (CBLOL)',
  LJL: 'League of Legends Japan League (LJL)',
};

export const lolTeams = [
  { abbreviation: 'fnatic', name: 'Fnatic' },
  { abbreviation: 'g2', name: 'G2 Esports' },
  { abbreviation: 'skt', name: 'T1 (formerly SK Telecom T1)' },
  { abbreviation: 'damwon', name: 'DAMWON Gaming' },
  { abbreviation: 'cloud9', name: 'Cloud9' },
  { abbreviation: 'tsm', name: 'Team SoloMid' },
  { abbreviation: 'rng', name: 'Royal Never Give Up (RNG)' },
  { abbreviation: 'fpx', name: 'FunPlus Phoenix (FPX)' },
  { abbreviation: 'edg', name: 'Edward Gaming (EDG)' },
  { abbreviation: 'gen_g', name: 'Gen.G Esports' },
  { abbreviation: 'liquid', name: 'Team Liquid' },
  { abbreviation: 'fnc', name: 'FunPlus Phoenix (FPX)' },
  { abbreviation: 'ig', name: 'Invictus Gaming (IG)' },
  { abbreviation: 'rogue', name: 'Rogue' },
  { abbreviation: 'vitality', name: 'Team Vitality' },
  { abbreviation: 'mad', name: 'MAD Lions' },
  { abbreviation: 'drx', name: 'DRX (DragonX)' },
  { abbreviation: 'immortals', name: 'Immortals' },
  { abbreviation: '100t', name: '100 Thieves' },
  { abbreviation: 'lgd', name: 'LGD Gaming' },
];
